# Generated by Django 4.1 on 2022-09-19 10:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todo',
            old_name='Data',
            new_name='Date',
        ),
    ]
